name = "Youn Mélois"
address = "Nantes, France"
title = "Software Engineer"
subtitle = "Real-Time Programming & Performance"

soft-skills = [
    { name = "Quick-witted" },
    { name = "Ambitious" },
    { name = "Cautious" },
    { name = "Organized" },
]

[contact]
email = "youn@melois.dev"
phone = "+33 7 83 54 37 48"
website = "melois.dev"
bluesky = "melois.dev"
linkedin = "youn-melois"

[[languages]]
name = "French"
level = "Native"

[[languages]]
name = "English (C1)"
level = "Professional"

[[hard-skills]]
name = "Rust"
examples = ["CLI", "FFI", "WebAssembly"]

[[hard-skills]]
name = "Operations"
examples = ["Ansible", "Docker", "OpenStack"]

[[hard-skills]]
name = "C/C++"
examples = ["GUI", "Qt"]

[[hard-skills]]
name = "Linux"
examples = ["Arch", "Bash"]

[[interests]]
name = "Computing"
examples = ["Open-source"]

[[interests]]
name = "Sports"
examples = ["Cycling"]

[[interests]]
name = "Reading"
examples = ["Comic", "Webtoon"]

[[interests]]
name = "Video Games"
examples = ["Sandbox", "Co-op"]

[[experiences]]
company = "Clever Cloud"
time = "(Oct. 2024 - Present)"
title = "Software Developer (Apprenticeship)"
link = "clever-cloud.com"

[[experiences]]
company = "Clever Cloud"
time = "(Jul. 2024 - Sep. 2024)"
title = "Software Developer (Internship)"

[[education]]
school = "ISEN Yncréa Ouest"
degree = "Engineering Degree, Software Engineering"
time = "(Sep. 2020 - Oct. 2025)"
link = "isen-nantes.fr"

[[education]]
school = "Sveučilište Algebra (Algebra University)"
degree = "Software Engineering"
time = "(Feb. 2024 - Jul. 2024)"
description = "One-semester Erasmus in Zagreb, Croatia."
link = "algebra.hr"

[[projects]]
title = "Manga Reader"
description = "Creation of a cross-platform (mobile/desktop) application for viewing mangas/webtoons from popular sources."
link = "github.com/midokuapp/midoku"
skills = ["Rust", "WebAssembly", "Dioxus"]

[[projects]]
title = "Rewriting Oodle in Rust"
description = "Oodle is a data compression algorithm used in many video games. This rewrite allows Oodle to be used in Rust applications without linking with the original C library."
link = "github.com/sehnryr/oodle-rs"
skills = ["Rust", "FFI", "Bindgen"]

[[projects]]
title = "Reverse Engineering Warframe's Cache"
description = "Extraction of the game's binary compressed data from Warframe to retrieve images and music. Creation of a TUI application to explore and extract this data."
link = "github.com/sehnryr/wfcache-api"
skills = ["Rust", "C++", "TUI", "ImHex"]

[[projects]]
title = "Open-source Contributions"
description = "Creating Issues and Pull Requests on open-source projects: dioxus, rust-bindgen, topgrade, cargo-component"
