name = "Youn Mélois"
address = "Nantes, France"
title = "Ingénieur Logiciel Rust"
subtitle = "Optimisation de performances bas niveau"

soft-skills = [
    { name = "Vif d'esprit" },
    { name = "Ambitieux" },
    { name = "Prudent" },
    { name = "Ordonné" },
]

[contact]
email = "youn@melois.dev"
phone = "+33 7 83 54 37 48"
website = "melois.dev"
bluesky = "melois.dev"
linkedin = "youn-melois"

[[languages]]
name = "Français"
level = "Natif"

[[languages]]
name = "Anglais (C1)"
level = "Professionnel"

[[hard-skills]]
name = "Rust"
examples = ["CLI", "FFI", "WebAssembly"]

[[hard-skills]]
name = "SQL"
examples = ["PostgreSQL", "SQLite"]

[[hard-skills]]
name = "C/C++"
examples = ["IHM", "Qt"]

[[hard-skills]]
name = "Linux"
examples = ["NixOS", "Nushell"]

[[interests]]
name = "Informatique"
examples = ["Open-source"]

[[interests]]
name = "Sport"
examples = ["Vélo"]

[[interests]]
name = "Lecture"
examples = ["Comic", "Webtoon"]

[[interests]]
name = "Jeux vidéo"
examples = ["Bac à Sable", "Coop"]

[[experiences]]
company = "Clever Cloud"
time = "(oct. 2024 - aujourd'hui)"
title = "Développeur logiciels en Alternance"
description = "Création d'une API pour la gestion des utilisateurs (alias: rôles) des add-ons PostgreSQL. Contribution au projet KMS (Key Management System) et de l'outilage interne en Rust."
link = "clever-cloud.com"
skills = ["Scala", "PostgreSQL", "Ruby", "Rust"]

[[experiences]]
company = "Clever Cloud"
time = "(juil. 2024 - sept. 2024)"
title = "Développeur logiciels en Stage"

[[education]]
school = "ISEN Yncréa Ouest"
degree = "Diplôme d'ingénieur, Ingénierie Logicielle"
time = "(sept. 2020 - sept. 2025)"
link = "isen-nantes.fr"

[[projects]]
title = "Réécriture d'un algorithme de compression en Rust"
description = "Oodle est un algorithme de compression de données utilisé dans de nombreux jeux vidéo. Cette réécriture permet d'utiliser Oodle dans des applications Rust sans avoir à faire du linkage avec la bibliothèque C originale."
link = "github.com/sehnryr/oodle-rs"
skills = ["Rust", "FFI", "Bindgen"]

[[projects]]
title = "Rétro-ingénierie du cache de Warframe"
description = "Extraction des données compressées binaires du jeu Warframe pour en récupérer les images et musiques. Création d'une application TUI pour explorer et extraire ces données."
link = "github.com/sehnryr/wfcache-api"
skills = ["Rust", "C++", "TUI", "ImHex"]

[[projects]]
title = "SSG en CLI pour rédiger ce CV"
description = "Générateur de site statique en ligne de commande pour la rédaction de ce CV. Il lit un fichier TOML et génère un fichier HTML+CSS minifié, optimisé pour l'impression et l'accessibilité."
link = "github.com/sehnryr/resume"
skills = ["Rust", "HTML", "CSS"]

[[projects]]
title = "Contributions Open-source"
description = "Création d'Issues et Pull Requests sur des projets open-source: dioxus, rust-bindgen, topgrade, cargo-component"
